### PR TITLE
I changed the cointype to 4343 to meet SLIP44 specifications.

### PR DESCRIPTION
**Pull request by xembook**
I think symbol's coin type is 4343
https://github.com/satoshilabs/slips/blob/master/slip-0044.md

could you please check this, thank you.

### CODE REVIEW

**Review by rg911 — CHANGES_REQUESTED** [review]
Travis CI failed. Would you be okay to have a look pls?

**Comment by xembook** [comment]
I added more commits on example dir.
but ,I realized that I needed to fix it further.

```
src\Wallet.ts(66):     public static DEFAULT_WALLET_PATH = 'm/44\'/43\'/0\'/0\'/0\'';
test\DerivationEd25519.spec.ts(75):              {path: 'm/44\'/43\'/0\'/0\'/0\'',
test\DerivationEd25519.spec.ts(78):              {path: 'm/44\'/43\'/1\'/0\'/0\'',
test\DerivationEd25519.spec.ts(98):              {path: 'm/44\'/43\'/0\'/0\'/0\'',
test\DerivationEd25519.spec.ts(101):              {path: 'm/44\'/43\'/1\'/0\'/0\'',
test\Wallet.spec.ts(125):         it('derive second account when given path m/44\'/43\'/1\'/0\'/0\'', () => {
test\Wallet.spec.ts(128):             const account = wallet.getChildAccount('m/44\'/43\'/1\'/0\'/0\'');
test\Wallet.spec.ts(168):         it('derive second account when given path m/44\'/43\'/1\'/0\'/0\'', () => {
test\Wallet.spec.ts(171):             const account = wallet.getChildPublicAccount('m/44\'/43\'/1\'/0\'/0\'');
```

however , this may have an impact on current projects. for example , using `DEFAULT_WALLET_PATH`
Please consider this for your team.

**Comment by rg911** [comment]
> I added more commits on example dir.
> but ,I realized that I needed to fix it further.
> 
> ```
> src\Wallet.ts(66):     public static DEFAULT_WALLET_PATH = 'm/44\'/43\'/0\'/0\'/0\'';
> test\DerivationEd25519.spec.ts(75):              {path: 'm/44\'/43\'/0\'/0\'/0\'',
> test\DerivationEd25519.spec.ts(78):              {path: 'm/44\'/43\'/1\'/0\'/0\'',
> test\DerivationEd25519.spec.ts(98):              {path: 'm/44\'/43\'/0\'/0\'/0\'',
> test\DerivationEd25519.spec.ts(101):              {path: 'm/44\'/43\'/1\'/0\'/0\'',
> test\Wallet.spec.ts(125):         it('derive second account when given path m/44\'/43\'/1\'/0\'/0\'', () => {
> test\Wallet.spec.ts(128):             const account = wallet.getChildAccount('m/44\'/43\'/1\'/0\'/0\'');
> test\Wallet.spec.ts(168):         it('derive second account when given path m/44\'/43\'/1\'/0\'/0\'', () => {
> test\Wallet.spec.ts(171):             const account = wallet.getChildPublicAccount('m/44\'/43\'/1\'/0\'/0\'');
> ```
> 
> however , this may have an impact on current projects. for example , using `DEFAULT_WALLET_PATH`
> Please consider this for your team.

**Comment by rg911** [comment]
> > I added more commits on example dir.
> > but ,I realized that I needed to fix it further.
> > ```
> > src\Wallet.ts(66):     public static DEFAULT_WALLET_PATH = 'm/44\'/43\'/0\'/0\'/0\'';
> > test\DerivationEd25519.spec.ts(75):              {path: 'm/44\'/43\'/0\'/0\'/0\'',
> > test\DerivationEd25519.spec.ts(78):              {path: 'm/44\'/43\'/1\'/0\'/0\'',
> > test\DerivationEd25519.spec.ts(98):              {path: 'm/44\'/43\'/0\'/0\'/0\'',
> > test\DerivationEd25519.spec.ts(101):              {path: 'm/44\'/43\'/1\'/0\'/0\'',
> > test\Wallet.spec.ts(125):         it('derive second account when given path m/44\'/43\'/1\'/0\'/0\'', () => {
> > test\Wallet.spec.ts(128):             const account = wallet.getChildAccount('m/44\'/43\'/1\'/0\'/0\'');
> > test\Wallet.spec.ts(168):         it('derive second account when given path m/44\'/43\'/1\'/0\'/0\'', () => {
> > test\Wallet.spec.ts(171):             const account = wallet.getChildPublicAccount('m/44\'/43\'/1\'/0\'/0\'');
> > ```
> > 
> > 
> > however , this may have an impact on current projects. for example , using `DEFAULT_WALLET_PATH`
> > Please consider this for your team.

Feel free to update them, we will handle the wallet part
thanks for the contributing 👍

**Comment by xembook** [comment]
thanks!
I tried to change all src and test from 43 to 4343.
I have also modified the test cases as needed.

could you please check these , thank you.

**Review by rg911 — APPROVED** [review]

**Pull request merged**
